spring:
  application:
    name: financetracker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/financetracker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true

  threads:
    virtual:
      enabled: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:3f8b2c9d7e4a1f6b0c5d8e2a9b4f7c1d3e6a0b5c8f2d7e4a1k6c9d0e3f8b2c}
      expiration: 86400000